### ISSUE TITLE
[0.5.2] リンク切れ "Redmineデフォルトの実績管理へ移動する"

### ISSUE THREAD

**Issue by yusukemasuda** [toritori0318/redmine_estimate_timelog#6]
Redmine をホストのルートでない場所（e.g: http://hostname/sub/redmine/）にインストールしている場合、集計ページにある 「Redmineデフォルトの実績管理へ移動する」のリンクが 404エラーとなります。

/app/views/estimate_timelog/_date_range.html.erb に記述の '/time_entries' というパスがルートからの絶対パスとなっているためかと思います。
当方では '../time_entries' と修正することで解決していますが、私自身 Ruby on Rails の知識がないため、これが ホストのルートにインストールした場合に正しく動作するのかわからなかったため、Pull Request ではなく、Issue に登録させていただきました。
この修正で問題なければ、Pull Request を送らせていただきます。

**Comment by toritori0318** [comment]
@yusukemasuda  レポートありがとうございます。
自分はRailsアプリをサブディレクトリ運用をしたことがないのですが、
Railsでは `RAILS_RELATIVE_URL_ROOT` 環境変数を指定して運用するようです。
こちらの方式であれば、以下のコードで問題なく動作しました。

```patch
diff --git app/views/estimate_timelog/_date_range.html.erb app/views/estimate_timelog/_date_range.html.erb
index 43433f5..b13cfd8 100644
--- app/views/estimate_timelog/_date_range.html.erb
+++ app/views/estimate_timelog/_date_range.html.erb
@@ -1,4 +1,4 @@
-<%= raw link_to(l(:et_label_redminedefault), '/time_entries' + if controller.action_name == 'report'; ('/' + controller.action_name) else '' end) if User.current.allowed_to?(:view_time_entries, nil, :global => true) %>
+<%= raw link_to(l(:et_label_redminedefault), (config.relative_url_root || '/') + '/time_entries' + if controller.action_name == 'report'; ('/' + controller.action_name) else '' end) if User.current.allowed_to?(:view_time_entries, nil, :global => true) %>
 <script type="text/javascript">
   $("#qury_form > form").submit(function() {
       alert('submit!!');
```

よろしければ、こちらのパッチを試していただいてもよいでしょうか？  
問題なければ本体にも適用いたします。

**Comment by yusukemasuda** [comment]
ありがとうございます。
確認して報告いたします。

**Comment by yusukemasuda** [comment]
確認いたしました。

ご提示いただいた修正で期待どおり動作しました。
一方で、以下のところが気になりました。

(config.relative_url_root || '/')

これは config.relative_url_root に値がないとき、、、ホストのルートディレクトリに配置されている場合、、、'/' が返り、その後ろの '/time_entries' の '/' と、'/' が重なってしまうのではないかと思いました。

**Comment by yusukemasuda** [comment]
上記修正は Redmine2系（0.5.2）に修正していただくことは可能でしょうか？

**Comment by toritori0318** [comment]
動作のご確認ありがとうございます。
0.5.x系用のブランチを切って対応してみます。少々お待ちください。  
> これは config.relative_url_root に値がないとき、、、ホストのルートディレクトリに配置されている場合、、、'/' が返り、その後ろの '/time_entries' の '/' と、'/' が重なってしまうのではないかと思いました。

一応動作検証したところでは特に問題無さそうでしたが、おっしゃるとおりなのでこちらは対応して修正します

**Comment by toritori0318** [comment]
@yusukemasuda 0.5.x系のリリースブランチを切りました > release-0.5.3  
以下で切り替えてお使いください。
```
git fetch --all
git checkout release-0.5.3
```

**Comment by yusukemasuda** [comment]
申し訳ありません。長らくログインしておらずクローズするのを忘れておりました。
対応ありがとうございます。
